### ISSUE TITLE
Inicializar projeto no transifex

### ISSUE THREAD

**Issue by ramiroluz** [scipy-latinamerica/scipyla2018-web#19]
Configurar a versão atual do site para iniciar tradução no transifex.

**Comment by olemis** [comment]
/me creating it . What will be the source language ? Portuguese or English ?

**Comment by olemis** [comment]
Done https://www.transifex.com/scipyla/scipyla-2018

**Comment by olemis** [comment]
Team created and @rgaiacs @xmnlab @ramiroluz added as admins
