### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2018-web#25]
![screenshot from 2018-02-22 11-58-19](https://user-images.githubusercontent.com/1506457/36537370-d20ba072-17c7-11e8-8f9a-6104d929d4c4.png)

Eu acho que em alguns lugares a font está pequena. Por exemplo, a descricao de "Programa", "Agenda" e "Organizadores".

**Comment by LuanComputacao** [comment]
I have made some modifications to fix the `font-size` in the pull request #41

**Comment by ramiroluz** [comment]
If this is still small we can reopen this later.
