### ISSUE TITLE
Encontrar imagem da rua das flores, Curitiba.

### ISSUE THREAD

**Issue by ramiroluz** [scipy-latinamerica/scipyla2018-web#3]
Encontrar uma imagem com permissão de uso para a imagem que está faltando, curitiba-rua-das-flores.png com as dimensões: 820 X 614.

**Comment by rgaiacs** [comment]
CC-BY

- https://flic.kr/p/61gsDK (minha favorita)
- https://flic.kr/p/au6DSE (minha segunda escolha)
- https://flic.kr/p/Bz1EN (minha terceira escolha)
- https://flic.kr/p/8LfHc5
- https://flic.kr/p/9FvKM9
- https://flic.kr/p/au3USz

> com as dimensões: 820 X 614

Você provavelmente consegue cortar as images que mencionei.

**Comment by ramiroluz** [comment]
CC-BY, devo dar os devidos créditos e indicar modificações, como faz isso num site que uso a foto como plano de fundo?

**Comment by rgaiacs** [comment]
**Nota**: Nada que eu escrever deve ser tomado como recomendacão jurídica. Você deve contrar um advogado especializado para assistência jurídica.

@ramiroluz Não existe uma forma padrão de dar os devidos créditos. :-( Algumas sugestões:

1. Você pode colocar metadados no arquivo da imagem dando os devidos créditos.
2. Você pode colocar uma nota no rodapé do site dando os créditos pela imagem.
3. Você pode editar a image para incluir os créditos.

Considerando um site responsivo, 3 não vai funcionar porque os créditos não estarão sempre visiveis. Algumas pessoas podem reclamar de 1. A melhor alternativa é 3. Só não sei como gerenciar isso no site.

**Comment by ramiroluz** [comment]
Escrevi um comentário para os autores das fotos.

**Comment by tadiane** [comment]
Para Rua XV encontrei poucas com licença para reutilização:
1) https://commons.wikimedia.org/wiki/File:Curitiba_PR_-_panoramio_(4).jpg
2) https://www.flickr.com/photos/radamesm/5894940965
3) https://pt.wikipedia.org/wiki/Pra%C3%A7a_Santos_Andrade#/media/File:Chafariz_Pra%C3%A7a_santos_andrade.JPG

**Comment by ramiroluz** [comment]
As imagens estão sob CC-BY 3.0 então precisamos apenas colocar uma citação, que pode ser uma marca d'água na própria imagem, #4 e #5 são a mesma coisa.

**Comment by ramiroluz** [comment]
Adicionei imagem com licença CC-BY e coloquei uma marca d'água na imagem, depois vou criar outra issue para melhorar isso. Devemos criar uma página de organizadores e colocar uma seção para esse tipo de créditos. por exemplo:
**Fotos cedidas por:**
- Foto: Fotógrafo - url
- Foto: Fotógrafo - url
