### ISSUE TITLE
The redirection of http://scipyla.org is outdated.

### ISSUE THREAD

**Issue by ramiroluz** [scipy-latinamerica/scipyla2018-web#36]
The link: http://scipyla.org is being redirected to http://scipyla.org/pt which is an old version of the conference (2016 I believe). Related to #33 and #35.

**Comment by leliel12** [comment]
No this is the page of the organization. The conference is in
Conf.scipyla.org
Scipyla.org/conf
Scipyla.org/conf/2018

**Comment by ramiroluz** [comment]
Ok, closing this issue.

But the site have some broken links when accessed with this url: http://scipyla.org/conf/2018/ 

These are working:
http://scipyla.org/conf/
http://conf.scipyla.org/
