### ISSUE TITLE
Encontrar imagem para parque tanguá, Curitiba.

### ISSUE THREAD

**Issue by ramiroluz** [scipy-latinamerica/scipyla2018-web#4]
Encontrar uma imagem com permissão de uso para a imagem que está faltando, curitiba-tangua.jpg com as dimensões: 4000 X 1622.

**Comment by tadiane** [comment]
Alternativas:
1) https://commons.wikimedia.org/wiki/File:Parque_Tangu%C3%A1,_Curitiba.jpg
2) https://commons.wikimedia.org/wiki/File:Tangu%C3%A1_Curitiba.jpg
3) https://commons.wikimedia.org/wiki/File:Parque_Tangu%C3%A1_-_Curitiba_-_panoramio_(2).jpg
Se optarem pela última, posso clareá-la.

**Comment by ramiroluz** [comment]
Adicionei imagem com licença CC-BY e coloquei uma marca d'água na imagem, depois vou criar outra issue para melhorar isso. Devemos criar uma página de organizadores e colocar uma seção para esse tipo de créditos. por exemplo:

**Fotos cedidas por:**
- Foto: Fotógrafo - url
- Foto: Fotógrafo - url
