### ISSUE TITLE
Home link is adding a / at the end.

### ISSUE THREAD

**Issue by ramiroluz** [scipy-latinamerica/scipyla2018-web#49]
To reproduce, click some page, faq for example.
Click on Início/Home, then the address bar shows an extra slash.

http://conf.scipyla.org//

**Comment by LuanComputacao** [comment]
Using a local server.
`$ python3 -m http.server 12007`
The slash is not added. I think that is an influence from the web server (Apache, Nginx, etc.).

**Comment by LuanComputacao** [comment]
It's really happening. I will fix is in a moment.

**Comment by LuanComputacao** [comment]
Solved
