### ISSUE TITLE
Encontrar imagem para jardim botânico, Curitiba.

### ISSUE THREAD

**Issue by ramiroluz** [scipy-latinamerica/scipyla2018-web#5]
Encontrar uma imagem com permissão de uso para a imagem que está faltando, jardim_botanico_curitiba.jpg com as dimensões: 1770 X 474.

**Comment by rgaiacs** [comment]
https://github.com/scipy-latinamerica/scipyla2018-web/issues/3#issuecomment-365939431

**Comment by ramiroluz** [comment]
Adicionei imagem com licença CC-BY e coloquei uma marca d'água na imagem, depois vou criar outra issue para melhorar isso. Devemos criar uma página de organizadores e colocar uma seção para esse tipo de créditos. por exemplo:

**Fotos cedidas por:**
- Foto: Fotógrafo - url
- Foto: Fotógrafo - url
