### ISSUE TITLE
HOSPEDAJEM E TRANSPORTE

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2018-web#73]
Quem é o ponto de contato? Mega Viagens Turismo?

**Comment by ramiroluz** [comment]
O ponto de contato é a Mega Viagens Turismo.

**Comment by rgaiacs** [comment]
http://scipyla.org/conf/2018/venue/lodging/ precisa mencionar isso de maneira mais clara.

> A agência Mega Viagens Turismo preparou alguns pacotes de hospedagem com preços diferenciados. Os valores apresentados compreendem 4 diárias, para saber o preço da diária basta dividir o valor por quatro.

Poderia ser escrito como

> A agência [Mega Viagens Turismo](http://www.megaviagenseturismo.com.br/) preparou alguns pacotes de hospedagem com preços diferenciados para participantes do SciPyLA. Contato deve ser feito diretamente com a Mega Viagens Turismo por meio de ...
>
> Os valores apresentados compreendem 4 diárias, para saber o preço da diária basta dividir o valor por quatro.

**Comment by ramiroluz** [comment]
Entendi, vou arrumar isso.
