### ISSUE TITLE
JS Errors

### ISSUE THREAD

**Issue by fernandommota** [scipy-latinamerica/scipyla2018-web#92]
hello,

When load the page looks like the angular scripts have some bug.

Example:

![screen shot 2018-08-15 at 15 16 09](https://user-images.githubusercontent.com/263414/44174744-0c8d2680-a0b2-11e8-840f-4f2fc3e17d78.png)

**Comment by olemis** [comment]
@isaacvr `markdown-it` seems to be removed , but still injected as dependency .

**Comment by isaacvr** [comment]
@olemis I don't think that is removed. It works perfectly for me locally.

**Comment by ramiroluz** [comment]
I asked @fernandommota to open this issue because I can't reproduce the error.

I can't see those errors accessing the website from my machine.

**Comment by fernandommota** [comment]
hello guys,

I'm attaching a example in a other machine with windows.

<img width="1432" alt="screen shot 2018-08-16 at 08 26 23" src="https://user-images.githubusercontent.com/263414/44208502-88c54f80-a12e-11e8-878c-2a8e6ea49b16.png">


So, what is your environment?, for me still has the problem.

**Comment by ramiroluz** [comment]
Ok, now I see the problem. Using this url http://scipyla.org/conf/2018/ 

This url is ok: http://conf.scipyla.org/

It may be related to absolute vs relative paths.

**Comment by fernandommota** [comment]
thanks @ramiroluz
